server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Route for the new Student List Microservice
        - id: student-list-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/admin/StudentListServlet/**
          filters:
            - RewritePath=/admin/StudentListServlet(?<remaining>.*), /api/students$\{remaining}

        # NEW ROUTE: For your original Add Student Monolith Servlet
        - id: student-add-monolith
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/admin/AddStudentServlet/**
          # No RewritePath filter here because it needs to hit the real Servlet name

eureka:
  client:
    service-url:
      defaultZone: https://radiant-taiga-56597.herokuapp.com/eureka/
    register-with-eureka: true
    fetch-registry: true